# Generated by Django 5.1.7 on 2025-03-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(unique=True, verbose_name='Позиция')),
                ('title_ru', models.CharField(verbose_name='Название на русском')),
                ('title_en', models.CharField(verbose_name='Название на английском')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода')),
                ('timing', models.IntegerField(verbose_name='Длительность')),
                ('trailer', models.URLField(verbose_name='Трейлер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, default='posters/Out_Of_Poster.jpg', null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('content', models.CharField(blank=True, choices=[('SERIAL', 'Сериал'), ('MOVIE', 'Фильм')], default='MOVIE', verbose_name='Медиа формат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('slug', models.SlugField(unique=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directors.directors', verbose_name='Режиссёр')),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
                'ordering': ['position'],
            },
        ),
    ]
