# Generated by Django 5.1.7 on 2025-03-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['title_ru', 'title_en'], 'verbose_name_plural': 'Фильмы'},
        ),
    ]
