# Generated by Django 5.1.7 on 2025-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('movies', '0003_alter_movies_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['position'], 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['title_ru', 'title_en'], name='movies_movi_title_r_6bc164_idx'),
        ),
    ]
