# Generated by Django 5.1.7 on 2025-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('movies', '0004_alter_movies_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movies',
            name='movies_movi_title_r_6bc164_idx',
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['title_ru'], name='movies_movi_title_r_221073_idx'),
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['title_en'], name='movies_movi_title_e_0e6acb_idx'),
        ),
    ]
