# Generated by Django 5.1.7 on 2025-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movies_movies_movi_title_r_6bc164_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
    ]
