# Generated by Django 5.1.7 on 2025-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
    ]
